version: "3.9"

services:
  web:
    image: nginx:latest
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - app-network
    depends_on:
      - php
      - db

  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: genbook
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 05092004
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d genbook"]
      interval: 2s
      retries: 15

  selenium:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - 4444:4444
      - 5900:5900
    networks:
      - app-network

  php_test:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
      selenium:
        condition: service_started
    environment:
      APP_ENV: testing
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: genbook
      DB_USERNAME: root
      DB_PASSWORD: 05092004

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
