services:
  web:
    image: nginx:latest
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - php
      - db

  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 2s
      retries: 15

  selenium:
    image: selenium/standalone-chrome-debug:latest
    container_name: selenium
    ports:
      - 4444:4444
      - 5900:5900
    networks:
      - app-network

  php_test:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db
      - selenium
    environment:
      APP_ENV: testing
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: genbook_test
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
