<form method="POST" action="/login" class="text-start">
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" name="user[email]" id="email" class="form-control" placeholder="email@escola.edu.br" required>
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Senha</label>
        <input type="password" name="user[password]" id="password" class="form-control" required>
        <div class="text-end mt-1">
            <a href="#" class="small">Esqueceu a senha?</a>
        </div>
    </div>
    <button type="submit" class="btn btn-primary w-100">Entrar</button>
</form>
