<div class="container mt-5 mb-5">
    <div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-4">
        <h2 class="fw-bold mb-0"><i class="bi bi-pencil-square me-2"></i>Editar Autor</h2>
        <a href="/authors" class="btn btn-outline-secondary d-flex align-items-center">
            <i class="bi bi-arrow-left me-1"></i> Voltar
        </a>
    </div>

    <form method="POST" action="<?= route('authors.update', ['id' => $author->id]) ?>">
        <div class="row g-3">

            <div class="col-md-6">
                <label class="form-label">Nome Completo</label>
                <input type="text" name="full_name" class="form-control"
                    value="<?= htmlspecialchars($author->full_name) ?>" required>
            </div>

            <div class="col-md-6">
                <label class="form-label">Nacionalidade</label>
                <input type="text" name="nationality" class="form-control"
                    value="<?= htmlspecialchars($author->nationality) ?>">
            </div>

            <div class="col-md-6">
                <label class="form-label">Data de Nascimento</label>
                <input type="date" name="birth_date" class="form-control"
                    value="<?= htmlspecialchars(date('Y-m-d', strtotime($author->birth_date))) ?>">
            </div>

            <div class="col-md-6">
                <label for="is_active" class="form-label">Status</label>
                <input id="is_active" type="text" class="form-control"
                    value="<?= $author->is_active ? 'Ativo' : 'Inativo' ?>" disabled>
            </div>


            <div class="col-md-12">
                <label class="form-label">Biografia</label>
                <textarea name="bio" class="form-control" rows="5"><?= htmlspecialchars($author->bio) ?></textarea>
            </div>

        </div>

        <div class="d-flex justify-content-end mt-4 gap-2">
            <form action="<?= route('authors.update', ['id' => $author->id]) ?>" method="POST">
                <!-- Spoofing do método HTTP PUT -->
                <input type="hidden" name="_method" value="PUT">
                <button type="submit" class="btn btn-success">
                    <i class="bi bi-check-circle"></i> Salvar Alterações
                </button>
            </form>
        </div>
    </form>
</div>