name: Continous Integration

on:
  push:
  # pull_request:
  #   types: [opened, synchronize, reopened]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: Setup Uploads assets permissions
        run: sudo chown -R www-data:www-data public/uploads

      - name: Setup storage permissions
        run: sudo chown -R www-data:www-data storage bootstrap/cache

      - name: Up containers
        run: ./run up:ci -d

      - name: Wait for DB
        run: |
          echo "Waiting for Postgres..."
          for i in {1..30}; do
            docker compose exec db pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE} && break
            sleep 2
          done

      - name: PHPUnit tests
        run: ./run tests

  acceptance_tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: Up containers
        run: ./run up -d

      - name: See containers
        run: ./run ps

  code_quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: PSR-4 Checker
        run: ./run composer dump-autoload --optimize --strict-psr

      - name: PHPCS
        run: ./run phpcs

      - name: PHPStan
        run: ./run phpstan