name: Continous Integration

on:
  push:
  # pull_request:
  #   types: [opened, synchronize, reopened]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: Setup Uploads assets permissions
        run: sudo chown -R www-data:www-data public/uploads

      - name: Up containers
        run: ./run up -d

      - name: See containers
        run: ./run ps

      - name: Wait for Postgres to be ready
        run: |
          echo "⏳ Aguardando Postgres iniciar..."
          for i in {1..20}; do
            if docker compose exec -T db pg_isready -U $DB_USERNAME > /dev/null 2>&1; then
              echo "✅ Postgres está pronto!"
              break
            fi
            echo "Tentando novamente ($i/20)..."
            sleep 2
          done

      - name: PHPUnit Units test
        run: ./run tests

  acceptance_tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: Up containers
        run: ./run up -d

      - name: See containers
        run: ./run ps

  code_quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: PSR-4 Checker
        run: ./run composer dump-autoload --optimize --strict-psr

      - name: PHPCS
        run: ./run phpcs

      - name: PHPStan
        run: ./run phpstan