name: Continuous Integration

on:
  push:

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:16
        env:
          POSTGRES_DB: genbook_test
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 05092004
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U root -d genbook_test"
          --health-interval=2s
          --health-timeout=5s
          --health-retries=15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: Up containers
        run: ./run up:ci -d

      - name: Run Unit Tests
        run: ./run tests

  acceptance_tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: Up containers
        run: ./run up -d

      - name: See containers
        run: ./run ps

  code_quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: PSR-4 Checker
        run: ./run composer dump-autoload --optimize --strict-psr

      - name: PHPCS
        run: ./run phpcs

      - name: PHPStan
        run: ./run phpstan
