<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GenBook</title>

    <!-- JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" 
            crossorigin="anonymous">
    </script>
    <script src="/assets/js/application.js"></script>

    <!-- CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
          rel="stylesheet" 
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="/assets/css/application.css">
    <link rel="stylesheet" href="/assets/css/login.css">
</head>

<body class="bg-light d-flex min-vh-100 m-0">
    <main class="container-fluid">
        <header class="mb-3">
            <h1 class="text-center text-primary">
                <a href="/home" class="nav-link">GenBook</a>
            </h1>

            <nav class="navbar navbar-expand-lg bg-light">
                <div class="ms-auto d-flex align-items-center">
                    <?php if ($user['admin']): ?>
                        <form action="/admin" method="GET" class="me-2">
                            <button type="submit" class="btn btn-primary">Admin</button>
                        </form>
                    <?php endif; ?>

                    <?php if ($user): ?>
                        <form action="/logout" method="GET">
                            <button type="submit" class="btn btn-danger">Sair</button>
                        </form>
                    <?php endif; ?>
                </div>
            </nav>
        </header>

        <?php require '_flash_message.phtml'; ?>
        <?php require $view; ?>
    </main>
</body>

</html>