<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="assets/images/favicon.ico" type="image/x-icon">
    <title>GenBook</title>



    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="assets/css/application.css">
</head>

<body>
    <div class="d-flex">
        <!-- Sidebar -->
        <div class="sidebar d-flex flex-column">
            <h5 class="mb-4"><i class="bi bi-journal-bookmark"></i><a href="/home" class="m-lg-1 text-reset text-decoration-none">GenBook</a></h5>
            <ul class="nav nav-pills flex-column mb-auto">
                <li class="nav-item"><a href="/home" class="nav-link">Dashboard</a></li>
                <li class="nav-item"><a href="/books" class="nav-link">Livros</a></li>
                <li class="nav-item"><a href="/materials" class="nav-link">Materiais</a></li>
                <li class="nav-item"><a href="/loans" class="nav-link">Empréstimos</a></li>
                <li class="nav-item"><a href="/users" class="nav-link">Usuários</a></li>
                <li class="nav-item"><a href="/reports" class="nav-link">Relatórios</a></li>
                <?php if ($user['admin']): ?>
                    <li class="nav-item">
                        <a href="/admin" class="nav-link">Admin</a>

                    </li>
                <?php endif; ?>

                <li class="nav-item mt-4"><strong>Sistema</strong></li>
                <li class="nav-item"><a href="/config" class="nav-link">Configurações</a></li>
                <li class="nav-item">
                    <a href="/logout" class="nav-link">
                        <i class="bi bi-box-arrow-right me-2"></i> Sair
                    </a>
                </li>

            </ul>

        </div>

        <!-- Conteúdo principal -->
        <div class="flex-grow-1 d-flex flex-column">
            <!-- Header -->
            <header class="header">
                    <button class="menu-button d-lg-none btn btn-outline-secondary" type="button">
    <i class="bi bi-list"></i>
</button>

                <div class="search-bar">
                    <div class="input-group">
                        <span class="input-group-text bg-white"><i class="bi bi-search"></i></span>
                        <input type="text" class="form-control" placeholder="Pesquisar...">
                    </div>
                </div>
                <div class="d-flex align-items-center gap-4">

                    <!-- Dropdown de Notificações -->
                    <div class="dropdown">
                        <a class="btn p-0 position-relative" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-bell fs-5"></i>
                            <span class="position-absolute top-0 start-100 translate-middle p-1 bg-danger border border-light rounded-circle dot"></span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li>
                                <h6 class="dropdown-header">Notificações</h6>
                            </li>
                            <li><a class="dropdown-item" href="#">Nova mensagem recebida</a></li>
                            <li><a class="dropdown-item" href="#">Solicitação aprovada</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Ver todas</a></li>
                        </ul>
                    </div>

                    <div class="d-flex align-items-center user-info">
                        <div class="avatar me-2">B</div>
                        <div class="d-flex flex-column">
                            <strong class="text-dark">Usuário</strong>
                            <small class="text-muted">Bibliotecário(a)</small>
                        </div>
                    </div>


                </div>
            </header>

            <!-- Conteúdo dinâmico -->
            <main class="content-area flex-grow-1">
                <?php require '_flash_message.phtml'; ?>
                <?php require $view; ?>
            </main>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
    <script src="/assets/js/application.js"></script>
</body>

</html>